version: '3'

services:
  app:
    build: .
    environment:
      - PORT=3000

  onion_service:
    build: onion_service
    depends_on:
      - app
    volumes:
      - ./torrc:/etc/tor/torrc
      - ./onion_service_volume:/var/lib/tor
